# Generated by Django 4.0.3 on 2022-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuenta', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha:')),
                ('nota', models.CharField(blank=True, max_length=100, verbose_name='Nota Explicativa:')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe:')),
            ],
        ),
    ]
